{% set version = '%s.0_%04i_%s'|format(GIT_DESCRIBE_TAG|replace('v', '') or '0.X.X', GIT_DESCRIBE_NUMBER|int, GIT_DESCRIBE_HASH or 'gUNKNOWN') %}

package:
  name: symbiyosys
  version: {{ version }}

source:
  - git_url: https://github.com/mballance/SymbiYosys.git
    folder: SymbiYosys
  - git_url: https://github.com/Boolector/boolector.git
    folder: boolector
    patches:
      - fixup_lingeling.patch
  - git_url: https://github.com/Z3Prover/z3.git
    folder: z3

build:
  detect_binary_files_with_prefix: True
  number: {{ environ.get('DATE_NUM') }}
  string: {{ environ.get('DATE_STR') }}
  script_env:
    - CI
    - TRAVIS

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - curl
    - gperf
    - gmp
  host:
    - yosys
  run:
    - yosys

test:
  files:
    - test/demo3.sby

about:
  home: http://symbiyosys.readthedocs.io
  license: ISC
  summary: 'SymbiYosys (sby) is a front-end driver program for Yosys-based formal hardware verification flows.'
